# syntax=docker/dockerfile:1.7
FROM node:20-alpine AS build

ARG BUILD_CONFIGURATION=production

WORKDIR /app
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY . .
RUN npm run build -- --configuration=${BUILD_CONFIGURATION}
FROM nginx:stable-alpine

COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD [ "nginx" , "-g", "daemon off;" ]