services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
      - db-network

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: development
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
volumes:
  postgres-data: